# render.yaml
services:
  - type: web
    name: gerador-cep-api
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
  - type: web
    name: puppeteer-service
    env: node
    plan: starter
    buildCommand: |
      apt-get update &&
      apt-get install -y wget gnupg &&
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&
      sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list' &&
      apt-get update &&
      apt-get install -y google-chrome-stable --no-install-recommends &&
      npm install
    startCommand: npm start
    repo: https://github.com/user/puppeteer-repo
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
    healthCheckPath: /
